### ISSUE TITLE
USER STORY: Change password

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#10]
As a **site user** I can **change my password** so that **I can stay secure**

## Acceptance Criteria:

* Acceptance Criteria 1: User selects forgot password on sign-in page
* Acceptance Criteria 2:  User redirected to Password reset page
* Acceptance Criteria 3:User enters email address
* Acceptance Criteria 4: Email reset sent to the user and redirected to the password reset notification 
* Acceptance Criteria 5: User, clicks on the reset link
* Acceptance Criteria 6: User is redirected to the password reset where they can enter their new password
* Acceptance Criteria 7: Flash message displayed to inform the user that password has been changed

# Tasks
- [x] Task 1 - Update templates for password reset
- [x] Task 2 Update settings
- [x] Task 3 - Update styling

#7
