### ISSUE TITLE
USER STORY: Log out

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#11]
As a **logged-in site user** I can **log out of my account** so that **other users cannot access my account**

## Acceptance Criteria:

* Acceptance Criteria 1: User clicks on sign out
* Acceptance Criteria 2: Flash message displayed that the user is signed out
* Acceptance Criteria 3: Sign in link is displayed
* Acceptance Criteria 4: User can not edit/delete posts 

## Tasks
- [x] Task 1 - Update Allauth template
- [x] Task 2 - Extend base
- [ ] Task 3 - Style as login

#7
