### ISSUE TITLE
USER STORY:  Welcome email

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#14]
As a **role** I can **capability** so that **received benefit**
As a **site user** I can **receive a welcome email** so that **I know that I have signed up correctly an feel like a valued user**

## Acceptance Criteria:

* Acceptance Criteria 1: Welcome email sent to registered email address
* Acceptance Criteria 2: User logged in
* Acceptance Criteria 3: Redirected to home page

## Tasks
- [x] Task 1: Update settings.py
- [x] Task 2: Create Signal
- [x] Task 3: Create view - create user
- [x] Task 4: Connect URL

#7
