### ISSUE TITLE
USER STORY: Topic

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#18]
As a **guest/logged-in site user,** I can **select a topic** so I can **view posts related to the topic**

## Acceptance Criteria:

* Acceptance Criteria 1: Users can select a topic from the navigation bar
* Acceptance Criteria 2: Redirected to post list page with a list of posts filtered by topic

## Tasks
- [ ] Task 1: Create template display all links in the topic list in the menu
- [ ] Task 2: Create view, Get topic, get posts by topic
- [ ] Task 3: Create Url (slug)

#15
