### ISSUE TITLE
USER STORY: View post list

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#19]
As a **guest/logged-in user** I can **view a list of posts** so that **I can select a post that interests me**

## Acceptance Criteria:

* Acceptance Criteria 1: User selects the topic from the menu
* Acceptance Criteria 2: list of posts displayed 
* Acceptance Criteria 3: user can select the post they would like to view
* Acceptance Criteria 4: Post is displayed  

## Tasks
- [x] Task 1 - Create view
- [x] Task 2 - Create template
- [ ] Task 3 - Style the template
- [x] Task 4 - connect url

#15
