### ISSUE TITLE
USER STORY: View post detail

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#21]
As a **guest/logged-in user** I  can **click on a post** so that **I can read the full article and related comments**

## Acceptance Criteria:

* Acceptance Criteria 1: User is able to click on a post
* Acceptance Criteria 2: Post details  are displayed, details include posted by username, created on, title, body, any images and comments

## Tasks
- [x] Task 1 - Create view
- [x] Task 2 - Create template
- [x] Task 3 - Style the template
- [x] Task 4 - connect url

#15
