### ISSUE TITLE
USER STORY: Navigation bar and footer

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#3]
As a **site user**  I can **intuitively navigate the site** so that **the layout of the site is consistent**

## Acceptance Criteria:

* Acceptance Criteria 1: The navigation bar is sticky
* Acceptance Criteria 2: Nav menu icon is displayed
* Acceptance Criteria 3: Site logo with a link back to home page
* Acceptance Criteria 4: Footer links with 'Contact Us', 'Talk Guidelines' & Social Media links
* Acceptance Criteria 5: Account icon is displayed, when clicked the menu is displayed
* Acceptance Criteria 5: Search icon is displayed, when clicked the search bar is displayed
* Acceptance Criteria 5: The Navigation bar and footer is fully responsive

# Tasks
- [x] Design the page layout using bootstrap and custom CSS
- [x] Create navigation bar using bootstrap and custom CSS
- [x] Create hamburger menu icon and create menu and links
- [x] Choose account logo and create a menu
- [x] Choose search icon and display, search bar for medium devices and above
- [x] Choose a site logo and add it to the navigation bar for medium devices and above
- [x] Create the footer with links - contact us and talk guidelines and style with CSS
- [x] Choose social media icon and style with CSS
- [x] Test the complete functionality

#2
