### ISSUE TITLE
USER STORY: API page

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#30]
As a **site user** I can **access reputable up to date data/support via a reliable and trustworthy source (such as the NHS/public health England)** so that **I am correctly informed and can stay up to date with statistics**

## Acceptance Criteria:

* Acceptance Criteria 1:  API information is displayed correctly
*  Acceptance Criteria 2:  Select date and information is displayed correctly

## Tasks
- [ ] Task 1 - create view -Get endpoint and response
- [ ] Task 2 - Get and filter data
- [ ] Task 3 - Create template
- [ ] Task4 - Connect to url

#29
