### ISSUE TITLE
USER STORY: API Errors

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#31]
As a **site user**, i can receive feedback if an API call fails, so that I receive a graceful UX and be correctly notified 

## Acceptance Criteria:

* Acceptance Criteria 1: Error message displayed

## Tasks
- [x] Task 1 - Create 500 error template
- [x] Task 2 - Create view, add a try except statement
- [x] Task 3 - connect url

#29
