### ISSUE TITLE
USER STORY: Contact us page

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#33]
As a **guest/logged-in site user** I can **complete a contact form so that I can provide feedback on posts to site admin where needed (report offending posts or express concern)** so that **appropriate action can be taken if needed**

## Acceptance Criteria:

* Acceptance Criteria 1: Users can fill out the form, required fields as a minimum
* Acceptance Criteria 2: Users can click send message
*  Acceptance Criteria 3: User receives message email sent
* Acceptance Criteria 4: Site admin receives an email

## Tasks
- [x] Task 1 Create view
- [x] Task 2 Creat template
- [x] Task 3 Connect Url

#29
