### ISSUE TITLE
USER STORY: About us page

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#35]
As a **guest/logged-in site user** I can **view the 'about us page** so that **I can understand more about the forum and its purpose**

## Acceptance Criteria:

* Acceptance Criteria 1: Paragraphs are displayed
* Acceptance Criteria 2: links to nhs and gov.uk display in separate tab

## Tasks
- [x] Task 1 Create view
- [x] Task 2 Create template
- [x] Task 3 Connect url

#34
