### ISSUE TITLE
USER STORY: Non-existent page or error

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#36]
As a **user** who is **directed to a non-existent page or resource**, I can **receive feedback and be redirected back to the main page automatically/smoothly without having to use the browser navigation buttons so that I have a streamlined UX**

## Acceptance Criteria:

* Acceptance Criteria 1: Error page displayed
* Acceptance Criteria 2: Redirected to home page if non-existent page In slug

## Tasks
- [x] Task 1 Create view
- [x] Task 2 Create template
- [x] Task 3 Connect url
