### ISSUE TITLE
USER STORY: Create new topics

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#38]
As a **site admin** I can **create  a new topic title on the Django admin page** so that **I can manage the site content for the best UX**

## Acceptance Criteria:

* Acceptance Criteria 1: In the Django admin page, add  a new topic title
* Acceptance Criteria 2:  Topic is  displayed in thenav menu

## Tasks
- [ ] Task 1 Setup model
- [ ] Task 2 Setup admin.py
- [ ] Task 3 Create the view
- [ ] Task 4  Render to the navbar

#37

**Comment by ccarabine** [comment]
This was completed in iteration 1
