### ISSUE TITLE
USER STORY: Search

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#4]
As a **site user** I can **search keywords** so that **I can locate posts**

## Acceptance Criteria:

* Acceptance Criteria 1: User can enter a keyword in the search bar
* Acceptance Criteria 2: List of posts are displayed
* Acceptance Criteria 3: Pagination links are displayed after 5 posts

# Tasks
- [x] Task 1: Update the model
- [x] Task 2:  Update the view with post list
- [x] Task 3: Create the code to search keywords
- [x] Task 4: Connect URL
- [x] Task 5: Test functionality 

#2
