### ISSUE TITLE
USER STORY: Manage users

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#41]
As a **site admin** I can restrict/delete a user account in django admin page if the content is offending or against 'talk guidelines'** so that **I can manage the site content for the best UX**

## Acceptance Criteria:

* Acceptance Criteria 1: In the Django admin page, admin can manage users
* Acceptance Criteria 2:  User is not be able to login if the account if deleted

## Tasks
- [ ] Task 1 - import User from django.contrib.auth.models 
- [ ] Task 2 -Add new user using django admin panel
- [ ] Task 3 - delete user using django admin panel

#37
