### ISSUE TITLE
USER STORY: Header and hero image

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#45]
As a **site user** I can **view the header and hero image** so that **I can learn more about the website and its purpose**

## Acceptance Criteria:

* Acceptance Criteria 1: Header paragraph displayed
* Acceptance Criteria 2: Hero images displayed with carousel
* Acceptance Criteria 3: Header and images are fully responsive

## Tasks
- [x] Task 1 - Create header, add text, style using CSS
- [x] Task 2 - Choose hero images, code carousel and display iamges
- [x] Task 3 - Use CSS/Bootstrap to ensure the header and hero images are fully responsive

#2
