### ISSUE TITLE
USER STORY: Navigation bar menu

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#5]
As a **site user** I can **click on the menu** so that **I can select topics and other pages to view**

## Acceptance Criteria:

* Acceptance Criteria 1: The user can select the menu icon 
* Acceptance Criteria 2: Menu is displayed
* Acceptance Criteria 3: The user can select a topic and is brought to the correct page
* Acceptance Criteria 4: The User can select a link to a page (lastest info from NHS, about ) and is brought to the correct page

# Tasks
- [ ] Task 1: Update template - Create menu using Bootstrap and CSS
- [ ] Task 2: Create links
- [ ] Task 3: Update Styling
- [ ] Task 4: Test the functionality

#2

**Comment by ccarabine** [comment]
finished in iteration 1 - didn't close
