### ISSUE TITLE
USER STORY: Talk Guidelines

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#51]
As a guest/logged-in site user I can view the 'talk guidelines page so that I can understand the rules

## Acceptance Criteria:

* Acceptance Criteria 1: Displays the page

## Tasks
- [x] Task 1 Create view
- [x] Task 2 Create template
- [ ] Task 3 Connect url
