### ISSUE TITLE
USER STORY: Privacy page

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#52]
As a guest/logged-in site user I can view the privacy page so that I can understand the rules

## Acceptance Criteria:

* Acceptance Criteria 1: Display page
* Acceptance Criteria 2:
* Acceptance Criteria 3:

## Tasks
- [x] Task 1 Create view
- [x] Task 2 Create template
- [x] Task 3 Connect URL
