### ISSUE TITLE
USER STORY: Log in

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#8]
As a **site user** I can **login with my username and password** so that **I can make comments on posts**

## Acceptance Criteria:

* Acceptance Criteria 1: User can click on the sign-in link on the navbar
* Acceptance Criteria 2: Log-in page is displayed
* Acceptance Criteria 3: If the username or password is incorrect a flash message is displayed to inform the user to re-enter
* Acceptance Criteria 4: If the user has entered the correct credentials, the user is redirected to the home page
* Acceptance Criteria 5: Users can make comments on posts
* Acceptance Criteria 6: Users can edit/delete a post (that they have created)

# Tasks
- [x] Task 1 - Install All auth and update settings
- [ ] Task 2 - Add links to navbar 
- [x] Task 3 - Add authentiation to posts and comment
- [x] Task 4 - Style form

#7
