### ISSUE TITLE
USER STORY: Log in with secure social media platforms

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/coronavirusforum#9]
As a **site user** I can  **login with Facebook or Google** so that **I can save time and login securely**

## Acceptance Criteria:

* Acceptance Criteria 1: User clicks on Facebook or Google button
* Acceptance Criteria 2: User enters their details
* Acceptance Criteria 3: Redirects to the home page if credentials are correct

# Tasks
- [x] Task 1 - Google - Add settings to settings.py
- [x] Task 2 - Get id and key from google and put in admin panel
- [x] Task 3 - Add button and style
- [x] Task4 - test to check its working
- [x]  Task 5 - Facebook - Add settings to settings.py
- [x] Task 6 - Get id and key from google and put in admin panel
- [x] Task 7 - Add button and style
- [ ] Task 8 -test to check its working
#7

**Comment by ccarabine** [comment]
Removed facebook functionality due to Not being able to fix - advised by tutor support
